# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

# VIO 9 corresponds to GPIO P2.9
CONFIG_APP_VIO_PIN=9

# @128 MHz clock this will create a 8 MHz block wave with 25% duty cycle.
CONFIG_APP_PULSE_HIGH_CYCLES=4
CONFIG_APP_PULSE_LOW_CYCLES=12
