#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_CLOCK_CONTROL_NRF=n

# Hardware support for ED25519
CONFIG_PSA_USE_CRACEN_HASH_DRIVER=y
CONFIG_PSA_USE_CRACEN_CIPHER_DRIVER=y

# Compatibility with for PM configuration after this line
CONFIG_PSA_USE_CRACEN_AEAD_DRIVER=y
CONFIG_PSA_USE_CRACEN_MAC_DRIVER=y

CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=y

CONFIG_NRFX_CLOCK=y
CONFIG_NRFX_CLOCK_LFXO_TWO_STAGE_ENABLED=y
CONFIG_NRFX_CLOCK_LF_SRC_XTAL=y

CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_FREQUENCY=32768
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_50PPM=y

CONFIG_NOTIFY=y
CONFIG_ONOFF=y
CONFIG_EARLY_CONSOLE=n

# Link Time Optimizations
CONFIG_ISR_TABLES_LOCAL_DECLARATION=n
CONFIG_LTO=n
