#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# P1: 26 (button0)
CONFIG_NRF_GPIO1_PIN_MASK_SECURE=0x04000000

CONFIG_NRF_TIMER10_SECURE=y
CONFIG_NRF_SPIM21_SECURE=y
CONFIG_NRF_GPIOTE20_SECURE=y
CONFIG_NRF_GPIOTE20_SECURE_CHANNELS_MASK=0x2
