#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Disable Protected Storage and ITS - not needed for this sample
CONFIG_TFM_PARTITION_PROTECTED_STORAGE=n
CONFIG_TFM_PARTITION_INTERNAL_TRUSTED_STORAGE=n

# Disable PSA crypto storage - keys are volatile only (no persistence)
CONFIG_MBEDTLS_PSA_CRYPTO_STORAGE_C=n

# Disable key derivation module
CONFIG_TFM_CRYPTO_KEY_DERIVATION_MODULE_ENABLED=n
