#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_UART=y

# Allow defining multiple USB CDC ACM interfaces.
CONFIG_CDC_ACM_SERIAL_MULTIPLE_INSTANCES=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y

# The sample requires UART async API that is not supported by the USB CDC ACM UART driver yet.
# Hence we need the UART async adapter as the intermediate layer.
CONFIG_UART_ASYNC_ADAPTER=y

# Indicate BLE traffic and log activity using LEDs.
CONFIG_GPIO=y
