;
; Copyright (c) 2023 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;

; ************
; AGNSS Request
; ************

net_info = {
	eci => uint,
	mcc => uint,
	mnc => uint,
	tac => uint,
	rsrp => int
}

agnss_req = {
	? types => [1*13 int],
	? filtered => bool,
	? mask => uint,
	? ni => net_info
}

types = 1
eci = 2
filtered = 3
mask = 4
mcc = 5
mnc = 6
rsrp = 7
tac = 8
ni = 9

; ***********************
; AGNSS Response is binary
; ***********************
