;
; Copyright (c) 2023 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;

; ************
; Send Message
; ************


; TODO: add DEVICE msg for networkInfo, simInfo, deviceInfo, serviceInfo?

pvt = {
	lat => float .size 8,
	lng => float .size 8,
	acc => float,
	? spd => float,
	? hdg => float,
	? alt => float
}

message_out = {
	appId => tstr,
	data => tstr/float/int/pvt,
	? ts => uint .size 8
}

appId = 1
data = 2
ts = 3
lat = 4
lng = 5
acc = 6
spd = 7
hdg = 8
alt = 9
