;
; Copyright (c) 2024 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;

; .. include_startingpoint_device_info_cddl_rst

stat = (SUCCESS: 0) /
	(INTERNAL_ERROR: 16781313) /
	(UNPROGRAMMED: 16781314)

operation = (READ_DEVICE_INFO: 0) /
	(UNSUPPORTED: 1)

device_info = [
    uuid: bstr .size 16,
    type: uint,
    testimprint: bstr .size 32,
    partno: uint,
    hwrevision: uint,
    productionrevision: uint,
]

read_req = (
      1,
      action: operation,
)

; Device Info service response to read data.
read_resp = (
      1,
      action: operation,
	status: stat,
	data: device_info,
)

device_info_req = [
      2,
      msg: (
            read_req
      ),
]

device_info_resp = [
      2,
      msg: (
            read_resp
      ),
]

; .. include_endingpoint_device_info_cddl_rst
