CONFIG_SOC_NRF54H20_CPURAD_ENABLE=y

# Radio notification connection callbacks are unavailable on the app core.
CONFIG_BT_RADIO_NOTIFICATION_CONN_CB=n

CONFIG_ZERO_LATENCY_LEVELS=1
CONFIG_SAMPLE_RTFW_IRQ_PRIORITY=0
