set(ZEPHYR_MCUBOOT_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/mcuboot)
set(ZEPHYR_MCUBOOT_KCONFIG   ${CMAKE_CURRENT_LIST_DIR}/mcuboot/Kconfig)
set(ZEPHYR_CDDL_GEN_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/cddl-gen)
set(ZEPHYR_CDDL_GEN_KCONFIG   ${CMAKE_CURRENT_LIST_DIR}/cddl-gen/Kconfig)
