/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_MISC_NORDIC_NRF_FICR_NRF9220_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_MISC_NORDIC_NRF_FICR_NRF9220_H_

#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_VSUP          0x40CU
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_COARSE_0      0x410U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_COARSE_1      0x414U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_COARSE_2      0x418U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_COARSE_3      0x41CU
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_COARSE_4      0x420U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_COARSE_5      0x424U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_FINE_0        0x428U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_FINE_1        0x42CU
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_FINE_2        0x430U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_FINE_3        0x434U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_FINE_4        0x438U
#define NRF_FICR_TRIM_APPLICATION_HSFLL_TRIM_FINE_5        0x43CU
#define NRF_FICR_TRIM_APPLICATION_MEMCONF_BLOCKTYPE_0_TRIM 0x444U
#define NRF_FICR_TRIM_APPLICATION_MEMCONF_BLOCKTYPE_1_TRIM 0x448U
#define NRF_FICR_TRIM_APPLICATION_MEMCONF_BLOCKTYPE_2_TRIM 0x44CU
#define NRF_FICR_TRIM_APPLICATION_MEMCONF_BLOCKTYPE_3_TRIM 0x450U

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_MISC_NORDIC_NRF_FICR_NRF9220_H_ */
