# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable SHA-256 algorithm for full modem FOTA
CONFIG_PSA_WANT_ALG_SHA_256=y
# These are needed to make it work with minimal TF-M
CONFIG_TFM_LOG_LEVEL_SILENCE=y
CONFIG_FOTA_DOWNLOAD_FULL_MODEM_BUF_SZ=512

# Full modem FOTA
CONFIG_DFU_TARGET=y
CONFIG_DFU_TARGET_STREAM=y
CONFIG_DFU_TARGET_FULL_MODEM=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y
CONFIG_ZCBOR=y
CONFIG_STREAM_FLASH_ERASE=y
CONFIG_STREAM_FLASH=y
CONFIG_FMFU_FDEV=y
CONFIG_DOWNLOADER_STACK_SIZE=2560
