#
# Copyright (c) 2022 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# LwM2M PGNSS overlay configuration, to be used in combination with overlay-lwm2m.conf and
# overlay-pgnss.conf

# LwM2M client
CONFIG_LWM2M_CLIENT_UTILS_LOCATION_ASSIST_PGNSS=y

# nRF Cloud PGNSS
CONFIG_NRF_CLOUD_PGNSS_TRANSPORT_NONE=y
CONFIG_NRF_CLOUD_PGNSS_DOWNLOAD_TRANSPORT_CUSTOM=y

# Disable throughput tools to save memory
CONFIG_MOSH_IPERF3=n
CONFIG_MOSH_CURL=n
