# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# NOT_SET profile is needed for SHA-256 support for full modem update
# but disable some features to reduce the size TF-M takes.
CONFIG_TFM_PROFILE_TYPE_NOT_SET=y
CONFIG_TFM_PARTITION_INTERNAL_TRUSTED_STORAGE=n

# Full modem FOTA
CONFIG_DFU_TARGET=y
CONFIG_DFU_TARGET_STREAM=y
CONFIG_DFU_TARGET_FULL_MODEM=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y
CONFIG_ZCBOR=y
CONFIG_STREAM_FLASH_ERASE=y
CONFIG_STREAM_FLASH=y
CONFIG_FMFU_FDEV=y
CONFIG_DOWNLOADER_STACK_SIZE=2560
CONFIG_MBEDTLS_LEGACY_CRYPTO_C=y
