#
# Copyright (c) 2021 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# PGNSS overlay configuration

# PGNSS
CONFIG_NRF_CLOUD_PGNSS=y
CONFIG_NRF_CLOUD_PGNSS_REPLACEMENT_THRESHOLD=4

# Storage for PGNSS
CONFIG_STREAM_FLASH=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_FCB=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_FCB=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y

# Library that maintains the current date and UTC time
CONFIG_DATE_TIME=y
