;
; Copyright (c) 2024 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;
ptr_buf = #6.32770(uint)
buf_len = #6.32771(uint)
ptr_attr = #6.32772(uint)
ptr_key = #6.32773(uint)
ptr_uint = #6.32774(uint)
ptr_cipher = #6.32775(uint)


psa_crypto_init_req = (
    10,
)

psa_get_key_attributes_req = (
    11,
    key: uint,
    p_attributes: ptr_attr,
)

psa_reset_key_attributes_req = (
    12,
    p_attributes: ptr_attr,
)

psa_purge_key_req = (
    13,
    key: uint,
)

psa_copy_key_req = (
    14,
    source_key: uint,
    p_attributes: ptr_attr,
    p_target_key: ptr_key,
)

psa_destroy_key_req = (
    15,
    key: uint,
)

psa_import_key_req = (
    16,
    p_attributes: ptr_attr,
    p_data: ptr_buf,
    data_length: buf_len,
    p_key: ptr_key,
)

psa_export_key_req = (
    17,
    key: uint,
    p_data: ptr_buf,
    data_size: buf_len,
    p_data_length: ptr_uint,
)

psa_export_public_key_req = (
    18,
    key: uint,
    p_data: ptr_buf,
    data_size: buf_len,
    p_data_length: ptr_uint,
)

psa_hash_compute_req = (
    19,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_hash: ptr_buf,
    hash_size: buf_len,
    p_hash_length: ptr_uint,
)

psa_hash_compare_req = (
    20,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_hash: ptr_buf,
    hash_length: buf_len,
)

psa_hash_setup_req = (
    21,
    p_handle: ptr_uint,
    alg: uint,
)

psa_hash_update_req = (
    22,
    p_handle: ptr_uint,
    p_input: ptr_buf,
    input_length: buf_len,
)

psa_hash_finish_req = (
    23,
    p_handle: ptr_uint,
    p_hash: ptr_buf,
    hash_size: buf_len,
    p_hash_length: ptr_uint,
)

psa_hash_verify_req = (
    24,
    p_handle: ptr_uint,
    p_hash: ptr_buf,
    hash_length: buf_len,
)

psa_hash_abort_req = (
    25,
    p_handle: ptr_uint,
)

psa_hash_clone_req = (
    26,
    handle: uint,
    p_handle: ptr_uint,
)

psa_mac_compute_req = (
    27,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_mac: ptr_buf,
    mac_size: buf_len,
    p_mac_length: ptr_uint,
)

psa_mac_verify_req = (
    28,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_mac: ptr_buf,
    mac_length: buf_len,
)

psa_mac_sign_setup_req = (
    29,
    p_handle: ptr_uint,
    key: uint,
    alg: uint,
)

psa_mac_verify_setup_req = (
    30,
    p_handle: ptr_uint,
    key: uint,
    alg: uint,
)

psa_mac_update_req = (
    31,
    p_handle: ptr_uint,
    p_input: ptr_buf,
    input_length: buf_len,
)

psa_mac_sign_finish_req = (
    32,
    p_handle: ptr_uint,
    p_mac: ptr_buf,
    mac_size: buf_len,
    p_mac_length: ptr_uint,
)

psa_mac_verify_finish_req = (
    33,
    p_handle: ptr_uint,
    p_mac: ptr_buf,
    mac_length: buf_len,
)

psa_mac_abort_req = (
    34,
    p_handle: ptr_uint,
)

psa_cipher_encrypt_req = (
    35,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_cipher_decrypt_req = (
    36,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_cipher_encrypt_setup_req = (
    37,
    p_handle: ptr_uint,
    key: uint,
    alg: uint,
)

psa_cipher_decrypt_setup_req = (
    38,
    p_handle: ptr_uint,
    key: uint,
    alg: uint,
)

psa_cipher_generate_iv_req = (
    39,
    p_handle: ptr_uint,
    p_iv: ptr_buf,
    iv_size: buf_len,
    p_iv_length: ptr_uint,
)

psa_cipher_set_iv_req = (
    40,
    p_handle: ptr_uint,
    p_iv: ptr_buf,
    iv_length: buf_len,
)

psa_cipher_update_req = (
    41,
    p_handle: ptr_uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_cipher_finish_req = (
    42,
    p_handle: ptr_uint,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_cipher_abort_req = (
    43,
    p_handle: ptr_uint,
)

psa_aead_encrypt_req = (
    44,
    key: uint,
    alg: uint,
    p_nonce: ptr_buf,
    nonce_length: buf_len,
    p_additional_data: ptr_buf,
    additional_data_length: buf_len,
    p_plaintext: ptr_buf,
    plaintext_length: buf_len,
    p_ciphertext: ptr_buf,
    ciphertext_size: buf_len,
    p_ciphertext_length: ptr_uint,
)

psa_aead_decrypt_req = (
    45,
    key: uint,
    alg: uint,
    p_nonce: ptr_buf,
    nonce_length: buf_len,
    p_additional_data: ptr_buf,
    additional_data_length: buf_len,
    p_ciphertext: ptr_buf,
    ciphertext_length: buf_len,
    p_plaintext: ptr_buf,
    plaintext_size: buf_len,
    p_plaintext_length: ptr_uint,
)

psa_aead_encrypt_setup_req = (
    46,
    p_handle: ptr_uint,
    key: uint,
    alg: uint,
)

psa_aead_decrypt_setup_req = (
    47,
    p_handle: ptr_uint,
    key: uint,
    alg: uint,
)

psa_aead_generate_nonce_req = (
    48,
    p_handle: ptr_uint,
    p_nonce: ptr_buf,
    nonce_size: buf_len,
    p_nonce_length: ptr_uint,
)

psa_aead_set_nonce_req = (
    49,
    p_handle: ptr_uint,
    p_nonce: ptr_buf,
    nonce_length: buf_len,
)

psa_aead_set_lengths_req = (
    50,
    p_handle: ptr_uint,
    ad_length: buf_len,
    plaintext_length: buf_len,
)

psa_aead_update_ad_req = (
    51,
    p_handle: ptr_uint,
    p_input: ptr_buf,
    input_length: buf_len,
)

psa_aead_update_req = (
    52,
    p_handle: ptr_uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_aead_finish_req = (
    53,
    p_handle: ptr_uint,
    p_ciphertext: ptr_buf,
    ciphertext_size: buf_len,
    p_ciphertext_length: ptr_uint,
    p_tag: ptr_buf,
    tag_size: buf_len,
    p_tag_length: ptr_uint,
)

psa_aead_verify_req = (
    54,
    p_handle: ptr_uint,
    p_plaintext: ptr_buf,
    plaintext_size: buf_len,
    p_plaintext_length: ptr_uint,
    p_tag: ptr_buf,
    tag_length: buf_len,
)

psa_aead_abort_req = (
    55,
    p_handle: ptr_uint,
)

psa_sign_message_req = (
    56,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_signature: ptr_buf,
    signature_size: buf_len,
    p_signature_length: ptr_uint,
)

psa_verify_message_req = (
    57,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_signature: ptr_buf,
    signature_length: buf_len,
)

psa_sign_hash_req = (
    58,
    key: uint,
    alg: uint,
    p_hash: ptr_buf,
    hash_length: buf_len,
    p_signature: ptr_buf,
    signature_size: buf_len,
    p_signature_length: ptr_uint,
)

psa_verify_hash_req = (
    59,
    key: uint,
    alg: uint,
    p_hash: ptr_buf,
    hash_length: buf_len,
    p_signature: ptr_buf,
    signature_length: buf_len,
)

psa_asymmetric_encrypt_req = (
    60,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_salt: ptr_buf,
    salt_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_asymmetric_decrypt_req = (
    61,
    key: uint,
    alg: uint,
    p_input: ptr_buf,
    input_length: buf_len,
    p_salt: ptr_buf,
    salt_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_key_derivation_setup_req = (
    62,
    p_handle: ptr_uint,
    alg: uint,
)

psa_key_derivation_get_capacity_req = (
    63,
    handle: uint,
    p_capacity: ptr_uint,
)

psa_key_derivation_set_capacity_req = (
    64,
    p_handle: ptr_uint,
    capacity: uint,
)

psa_key_derivation_input_bytes_req = (
    65,
    p_handle: ptr_uint,
    step: uint,
    p_data: ptr_buf,
    data_length: buf_len,
)

psa_key_derivation_input_integer_req = (
    66,
    p_handle: ptr_uint,
    step: uint,
    value: uint,
)

psa_key_derivation_input_key_req = (
    67,
    p_handle: ptr_uint,
    step: uint,
    key: uint,
)

psa_key_derivation_key_agreement_req = (
    68,
    p_handle: ptr_uint,
    step: uint,
    private_key: uint,
    p_peer_key: ptr_buf,
    peer_key_length: buf_len,
)

psa_key_derivation_output_bytes_req = (
    69,
    p_handle: ptr_uint,
    p_output: ptr_buf,
    output_length: buf_len,
)

psa_key_derivation_output_key_req = (
    70,
    p_attributes: ptr_attr,
    p_handle: ptr_uint,
    p_key: ptr_key,
)

psa_key_derivation_abort_req = (
    71,
    p_handle: ptr_uint,
)

psa_raw_key_agreement_req = (
    72,
    alg: uint,
    private_key: uint,
    p_peer_key: ptr_buf,
    peer_key_length: buf_len,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_generate_random_req = (
    73,
    p_output: ptr_buf,
    output_size: buf_len,
)

psa_generate_key_req = (
    74,
    p_attributes: ptr_attr,
    p_key: ptr_key,
)

psa_pake_setup_req = (
    79,
    p_handle: ptr_uint,
    password_key: uint,
    p_cipher_suite: ptr_cipher,
)

psa_pake_set_role_req = (
    80,
    p_handle: ptr_uint,
    role: uint,
)

psa_pake_set_user_req = (
    81,
    p_handle: ptr_uint,
    p_user_id: ptr_buf,
    user_id_len: buf_len,
)

psa_pake_set_peer_req = (
    82,
    p_handle: ptr_uint,
    p_peer_id: ptr_buf,
    peer_id_len: buf_len,
)

psa_pake_set_context_req = (
    83,
    p_handle: ptr_uint,
    p_context: ptr_buf,
    context_len: buf_len,
)

psa_pake_output_req = (
    84,
    p_handle: ptr_uint,
    step: uint,
    p_output: ptr_buf,
    output_size: buf_len,
    p_output_length: ptr_uint,
)

psa_pake_input_req = (
    85,
    p_handle: ptr_uint,
    step: uint,
    p_input: ptr_buf,
    input_length: buf_len,
)

psa_pake_get_shared_key_req = (
    86,
    p_handle: ptr_uint,
    p_attributes: ptr_attr,
    p_key: ptr_key,
)

psa_pake_abort_req = (
    87,
    p_handle: ptr_uint,
)

psa_crypto_req = [
    ; Union of different requests
    msg: (
        psa_crypto_init_req /
        psa_get_key_attributes_req /
        psa_reset_key_attributes_req /
        psa_purge_key_req /
        psa_copy_key_req /
        psa_destroy_key_req /
        psa_import_key_req /
        psa_export_key_req /
        psa_export_public_key_req /
        psa_hash_compute_req /
        psa_hash_compare_req /
        psa_hash_setup_req /
        psa_hash_update_req /
        psa_hash_finish_req /
        psa_hash_verify_req /
        psa_hash_abort_req /
        psa_hash_clone_req /
        psa_mac_compute_req /
        psa_mac_verify_req /
        psa_mac_sign_setup_req /
        psa_mac_verify_setup_req /
        psa_mac_update_req /
        psa_mac_sign_finish_req /
        psa_mac_verify_finish_req /
        psa_mac_abort_req /
        psa_cipher_encrypt_req /
        psa_cipher_decrypt_req /
        psa_cipher_encrypt_setup_req /
        psa_cipher_decrypt_setup_req /
        psa_cipher_generate_iv_req /
        psa_cipher_set_iv_req /
        psa_cipher_update_req /
        psa_cipher_finish_req /
        psa_cipher_abort_req /
        psa_aead_encrypt_req /
        psa_aead_decrypt_req /
        psa_aead_encrypt_setup_req /
        psa_aead_decrypt_setup_req /
        psa_aead_generate_nonce_req /
        psa_aead_set_nonce_req /
        psa_aead_set_lengths_req /
        psa_aead_update_ad_req /
        psa_aead_update_req /
        psa_aead_finish_req /
        psa_aead_verify_req /
        psa_aead_abort_req /
        psa_sign_message_req /
        psa_verify_message_req /
        psa_sign_hash_req /
        psa_verify_hash_req /
        psa_asymmetric_encrypt_req /
        psa_asymmetric_decrypt_req /
        psa_key_derivation_setup_req /
        psa_key_derivation_get_capacity_req /
        psa_key_derivation_set_capacity_req /
        psa_key_derivation_input_bytes_req /
        psa_key_derivation_input_integer_req /
        psa_key_derivation_input_key_req /
        psa_key_derivation_key_agreement_req /
        psa_key_derivation_output_bytes_req /
        psa_key_derivation_output_key_req /
        psa_key_derivation_abort_req /
        psa_raw_key_agreement_req /
        psa_generate_random_req /
        psa_generate_key_req /
        psa_pake_setup_req /
        psa_pake_set_role_req /
        psa_pake_set_user_req /
        psa_pake_set_peer_req /
        psa_pake_set_context_req /
        psa_pake_output_req /
        psa_pake_input_req /
        psa_pake_get_shared_key_req /
        psa_pake_abort_req
    ),
]

psa_crypto_rsp = [
    id: uint,
    status: int
]
