# P2P autonomous Group Owner with echo server.
# Build: -DEXTRA_CONF_FILE=overlay-echo-go.conf
CONFIG_SAMPLE_P2P_GO_MODE=y
CONFIG_SAMPLE_P2P_CONNECTION_METHOD_PBC=y
CONFIG_SAMPLE_P2P_ECHO_SERVER_MODE=y

# Serve DHCP without also running a DHCP client on the same interface.
CONFIG_NET_DHCPV4=n
