#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_HW_STACK_PROTECTION=n
CONFIG_BOOT_WATCHDOG_FEED=n
CONFIG_TICKLESS_KERNEL=y
CONFIG_FPROTECT=n
CONFIG_MCUBOOT_CLEANUP_RAM=y
