#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_SAMPLE_BT_CENTRAL_HIDS_PERIPHERAL_COUNT=2

# Currently the lowest achievable effective connection interval for two simultaneously transmitting
# peripherals is 1.5 ms (12 * 125 us).
# This is due to the connection events being scheduled in a round-robin fashion
# with the minimum achievable connection interval of 750 us per peripheral resulting from controller
# limitations.
# Attempts to go below this interval will result in a lower report rate.
CONFIG_SAMPLE_CENTRAL_HIDS_SCI_INTERVAL_MIN_125US=12

# To achieve the 1.5 ms connection interval, updating to the lowest supported frame space
# is required.
CONFIG_BT_FRAME_SPACE_UPDATE=y
