#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# MCUboot compression support with RAM-minimized LZMA parameters.
# Matches sysbuild/mcuboot/boards/nrf54ls05dk_nrf54ls05b_cpuapp.conf plus
# nrf54ls05 SOC LZMA defaults from Kconfig.defconfig.nrf54ls05_a_b_cpuapp.

CONFIG_NRF_COMPRESS=y
CONFIG_NRF_COMPRESS_DECOMPRESSION=y
CONFIG_NRF_COMPRESS_LZMA=y
CONFIG_NRF_COMPRESS_ARM_THUMB=y

CONFIG_NRF_COMPRESS_LZMA_MAX_DICT_SIZE=8192
CONFIG_NRF_COMPRESS_LZMA_LC=0
CONFIG_NRF_COMPRESS_LZMA_LP=0
CONFIG_NRF_COMPRESS_LZMA_MAX_LC_LP=0
