#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_FLASH=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_CRC=y
CONFIG_MULTITHREADING=n

# # Enable logging
CONFIG_LOG=y
# This is needed for logs to be printed because of CONFIG_MULTITHREADING=n
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_NCS_BOOT_BANNER=n

CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
