# Enable MCUboot bootloader support
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# Enable direct XIP with revert support
SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP_WITH_REVERT=y

SB_CONFIG_NCS_MCUBOOT_LOAD_PERIPHCONF=y
SB_CONFIG_NCS_MCUBOOT_MPCCONF_STATIC_WRITE_PROTECTION=y
