/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef FP_FHN_KCONFIG_COMPAT_H_
#define FP_FHN_KCONFIG_COMPAT_H_

/*
 * Kconfig compatibility layer for the FMDN to FHN rename.
 *
 * When the deprecated BT_FAST_PAIR_FMDN Kconfig tree is active,
 * this header maps all CONFIG_BT_FAST_PAIR_FMDN_* symbols to the
 * corresponding CONFIG_BT_FAST_PAIR_FHN_* symbols so that the
 * implementation sources can use only the FHN naming.
 */

#ifdef CONFIG_BT_FAST_PAIR_FMDN

#define CONFIG_BT_FAST_PAIR_FHN 1

/* Int options. */
#define CONFIG_BT_FAST_PAIR_FHN_TX_POWER \
	CONFIG_BT_FAST_PAIR_FMDN_TX_POWER
#define CONFIG_BT_FAST_PAIR_FHN_TX_POWER_CORRECTION_VAL \
	CONFIG_BT_FAST_PAIR_FMDN_TX_POWER_CORRECTION_VAL
#define CONFIG_BT_FAST_PAIR_FHN_MAX_CONN \
	CONFIG_BT_FAST_PAIR_FMDN_MAX_CONN
#define CONFIG_BT_FAST_PAIR_FHN_ECC_LEN \
	CONFIG_BT_FAST_PAIR_FMDN_ECC_LEN
#define CONFIG_BT_FAST_PAIR_FHN_RANDOM_NONCE_LEN \
	CONFIG_BT_FAST_PAIR_FMDN_RANDOM_NONCE_LEN
#define CONFIG_BT_FAST_PAIR_FHN_AUTH_SEG_LEN \
	CONFIG_BT_FAST_PAIR_FMDN_AUTH_SEG_LEN
#define CONFIG_BT_FAST_PAIR_FHN_VERSION_MAJOR \
	CONFIG_BT_FAST_PAIR_FMDN_VERSION_MAJOR
#define CONFIG_BT_FAST_PAIR_FHN_BATTERY_LEVEL_CRITICAL_THR \
	CONFIG_BT_FAST_PAIR_FMDN_BATTERY_LEVEL_CRITICAL_THR
#define CONFIG_BT_FAST_PAIR_FHN_BATTERY_LEVEL_LOW_THR \
	CONFIG_BT_FAST_PAIR_FMDN_BATTERY_LEVEL_LOW_THR
#define CONFIG_BT_FAST_PAIR_FHN_CLOCK_NVM_UPDATE_TIME \
	CONFIG_BT_FAST_PAIR_FMDN_CLOCK_NVM_UPDATE_TIME
#define CONFIG_BT_FAST_PAIR_FHN_CLOCK_NVM_UPDATE_RETRY_TIME \
	CONFIG_BT_FAST_PAIR_FMDN_CLOCK_NVM_UPDATE_RETRY_TIME
#define CONFIG_BT_FAST_PAIR_FHN_DULT_INTEGRATION_INIT_PRIORITY \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_INTEGRATION_INIT_PRIORITY
#define CONFIG_BT_FAST_PAIR_FHN_DULT_INTEGRATION_INIT_PRIORITY_LATE \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_INTEGRATION_INIT_PRIORITY_LATE
#define CONFIG_BT_FAST_PAIR_FHN_DULT_ACCESSORY_CATEGORY \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_ACCESSORY_CATEGORY
#define CONFIG_BT_FAST_PAIR_FHN_DULT_FIRMWARE_VERSION_MAJOR \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_FIRMWARE_VERSION_MAJOR
#define CONFIG_BT_FAST_PAIR_FHN_DULT_FIRMWARE_VERSION_MINOR \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_FIRMWARE_VERSION_MINOR
#define CONFIG_BT_FAST_PAIR_FHN_DULT_FIRMWARE_VERSION_REVISION \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_FIRMWARE_VERSION_REVISION
#define CONFIG_BT_FAST_PAIR_FHN_READ_MODE_FHN_RECOVERY_TIMEOUT \
	CONFIG_BT_FAST_PAIR_FMDN_READ_MODE_FMDN_RECOVERY_TIMEOUT
#define CONFIG_BT_FAST_PAIR_FHN_RING_REQ_TIMEOUT_DULT_BT_GATT \
	CONFIG_BT_FAST_PAIR_FMDN_RING_REQ_TIMEOUT_DULT_BT_GATT
#define CONFIG_BT_FAST_PAIR_FHN_RING_REQ_TIMEOUT_DULT_MOTION_DETECTOR \
	CONFIG_BT_FAST_PAIR_FMDN_RING_REQ_TIMEOUT_DULT_MOTION_DETECTOR

/* String options. */
#define CONFIG_BT_FAST_PAIR_FHN_DULT_MANUFACTURER_NAME \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_MANUFACTURER_NAME
#define CONFIG_BT_FAST_PAIR_FHN_DULT_MODEL_NAME \
	CONFIG_BT_FAST_PAIR_FMDN_DULT_MODEL_NAME

/* Bool options: map each defined FMDN bool to FHN equivalent. */
#ifdef CONFIG_BT_FAST_PAIR_FMDN_ECC_SECP160R1
#define CONFIG_BT_FAST_PAIR_FHN_ECC_SECP160R1 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_ECC_SECP256R1
#define CONFIG_BT_FAST_PAIR_FHN_ECC_SECP256R1 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_RING_COMP_NONE
#define CONFIG_BT_FAST_PAIR_FHN_RING_COMP_NONE 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_RING_COMP_ONE
#define CONFIG_BT_FAST_PAIR_FHN_RING_COMP_ONE 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_RING_COMP_TWO
#define CONFIG_BT_FAST_PAIR_FHN_RING_COMP_TWO 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_RING_COMP_THREE
#define CONFIG_BT_FAST_PAIR_FHN_RING_COMP_THREE 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_RING_VOLUME
#define CONFIG_BT_FAST_PAIR_FHN_RING_VOLUME 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_AUTH
#define CONFIG_BT_FAST_PAIR_FHN_AUTH 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_BATTERY
#define CONFIG_BT_FAST_PAIR_FHN_BATTERY 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_BATTERY_DULT
#define CONFIG_BT_FAST_PAIR_FHN_BATTERY_DULT 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_BEACON_ACTIONS
#define CONFIG_BT_FAST_PAIR_FHN_BEACON_ACTIONS 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_CALLBACKS
#define CONFIG_BT_FAST_PAIR_FHN_CALLBACKS 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_CLOCK
#define CONFIG_BT_FAST_PAIR_FHN_CLOCK 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_DULT
#define CONFIG_BT_FAST_PAIR_FHN_DULT 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_DULT_INTEGRATION
#define CONFIG_BT_FAST_PAIR_FHN_DULT_INTEGRATION 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_DULT_CAPABILITY_PLAY_SOUND
#define CONFIG_BT_FAST_PAIR_FHN_DULT_CAPABILITY_PLAY_SOUND 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_DULT_CAPABILITY_MOTION_DETECTOR_UT
#define CONFIG_BT_FAST_PAIR_FHN_DULT_CAPABILITY_MOTION_DETECTOR_UT 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_DULT_CAPABILITY_ID_LOOKUP_BLE
#define CONFIG_BT_FAST_PAIR_FHN_DULT_CAPABILITY_ID_LOOKUP_BLE 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_DULT_MOTION_DETECTOR
#define CONFIG_BT_FAST_PAIR_FHN_DULT_MOTION_DETECTOR 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_READ_MODE
#define CONFIG_BT_FAST_PAIR_FHN_READ_MODE 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_RING
#define CONFIG_BT_FAST_PAIR_FHN_RING 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_STATE
#define CONFIG_BT_FAST_PAIR_FHN_STATE 1
#endif

#ifdef CONFIG_BT_FAST_PAIR_FMDN_CRYPTO
#define CONFIG_BT_FAST_PAIR_FHN_CRYPTO 1
#endif

#endif /* CONFIG_BT_FAST_PAIR_FMDN */

#endif /* FP_FHN_KCONFIG_COMPAT_H_ */
