# Copyright (c) 2025 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Configuration overlay for uicr image

# Enable PROTECTEDMEM
CONFIG_GEN_UICR_PROTECTEDMEM=y

# Enable secondary firmware that boots on integrity failure
CONFIG_GEN_UICR_SECONDARY=y

# Enable SECONDARY.PROTECTEDMEM
CONFIG_GEN_UICR_SECONDARY_PROTECTEDMEM=y
