;
; Copyright (c) 2021 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: Apache-2.0
;


Timestamp = bstr .size 8
Test = [
    name: [ +tstr ],
    timestamp: Timestamp,
    types: ((unit: 1) / (something: 2) / (other: 3)),
]
