#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# ipc_radio in cpurad TCM via radio_loader; no MCUboot (no signed merge, no DFU).
SB_CONFIG_PPP_IPC_RADIO_TCM=y
SB_CONFIG_NETCORE_REMOTE=y
SB_CONFIG_NRF_RADIO_LOADER=y

SB_CONFIG_BOOTLOADER_NONE=y
SB_CONFIG_BOOTLOADER_MCUBOOT=n
