# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: Apache-2.0
#

set_config_bool(${image} CONFIG_BOOTLOADER_MCUBOOT "${SB_CONFIG_BOOTLOADER_MCUBOOT}")
set_config_bool(${image} CONFIG_NCS_MCUBOOT_APPLICATION_MANUFACTURING_APP "${SB_CONFIG_NRF_MANUFACTURING_APP}")
set_config_string(${image} CONFIG_MCUBOOT_SIGNATURE_KEY_FILE
                  "${SB_CONFIG_NRF_BOOT_MANUFACTURING_APP_SIGNATURE_KEY_FILE}"
)

if(SB_CONFIG_BOOTLOADER_MCUBOOT)
  if("${SB_CONFIG_SIGNATURE_TYPE}" STREQUAL "NONE")
    set_config_bool(${image} CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE y)
  else()
    set_config_bool(${image} CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE n)
  endif()

  if(SB_CONFIG_MCUBOOT_MODE_SINGLE_APP)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_SINGLE_APP y)
  elseif(SB_CONFIG_MCUBOOT_MODE_SWAP_USING_OFFSET)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_SWAP_USING_OFFSET y)
  elseif(SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_SWAP_USING_MOVE y)
  elseif(SB_CONFIG_MCUBOOT_MODE_SWAP_SCRATCH)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_SWAP_SCRATCH y)
  elseif(SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_OVERWRITE_ONLY y)
  elseif(SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_DIRECT_XIP y)
  elseif(SB_CONFIG_MCUBOOT_MODE_DIRECT_XIP_WITH_REVERT)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_DIRECT_XIP_WITH_REVERT y)
  elseif(SB_CONFIG_MCUBOOT_MODE_RAM_LOAD)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD y)
    set_config_bool(${image} CONFIG_XIP n)
    set_config_int(${image} CONFIG_FLASH_SIZE 0)
  elseif(SB_CONFIG_MCUBOOT_MODE_RAM_LOAD_WITH_REVERT)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD_WITH_REVERT y)
    set_config_bool(${image} CONFIG_XIP n)
    set_config_int(${image} CONFIG_FLASH_SIZE 0)
  elseif(SB_CONFIG_MCUBOOT_MODE_SINGLE_APP_RAM_LOAD)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_SINGLE_APP_RAM_LOAD y)
  elseif(SB_CONFIG_MCUBOOT_MODE_FIRMWARE_UPDATER)
    set_config_bool(${image} CONFIG_MCUBOOT_BOOTLOADER_MODE_FIRMWARE_UPDATER y)
  endif()
endif()
