#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Overlay for enabling delta modem FOTA.
# See https://docs.nrfcloud.com/docs/mcu/nrf-modem-fota for full setup instructions.

CONFIG_MEMFAULT_FOTA_MODEM_UPDATE=y

# Not required if the modem firmware project key is set at runtime from the nRF Cloud device shadow via the "memfaultModemKey" control.
# Uncomment to configure the project key at build time.
# CONFIG_MEMFAULT_FOTA_MODEM_PROJECT_KEY="YOUR_MODEM_PROJECT_KEY"
