#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

## TF-M: SFN mode with MM-IOVEC (see prj.conf) to keep RAM usage down for CoAP.
CONFIG_TFM_IPC=n
CONFIG_TFM_SFN=y
CONFIG_TFM_CRYPTO_CONC_OPER_NUM=4

## Additional date_time settings for CoAP
CONFIG_DATE_TIME_NTP=y
CONFIG_DATE_TIME_LOG_LEVEL_DBG=y

## Configure MBEDTLS for CoAP/DTLS
CONFIG_MQTT_LIB_TLS=n
CONFIG_MBEDTLS_DTLS=y
CONFIG_MBEDTLS_SSL_SRV_C=y
CONFIG_MBEDTLS_SSL_COOKIE_C=y
# Ciphersuite for CoAP
CONFIG_MBEDTLS_CIPHERSUITE_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256=y
CONFIG_MBEDTLS_SSL_DTLS_HELLO_VERIFY=y
CONFIG_MBEDTLS_SSL_DTLS_CONNECTION_ID=y
CONFIG_NET_SOCKETS_ENABLE_DTLS=y

## Memory allocation
CONFIG_NRF_WIFI_CTRL_HEAP_SIZE=20000
CONFIG_NRF_WIFI_DATA_HEAP_SIZE=92856

## Thread stack sizes

CONFIG_APPLICATION_THREAD_STACK_SIZE=4096
CONFIG_CONNECTION_THREAD_STACK_SIZE=6144
CONFIG_NET_MGMT_EVENT_STACK_SIZE=8192
CONFIG_WIFI_NM_WPA_SUPPLICANT_THREAD_STACK_SIZE=6144
CONFIG_NET_CONNECTION_MANAGER_MONITOR_STACK_SIZE=5120
CONFIG_L2_WIFI_CONN_WQ_STACK_SIZE=512
CONFIG_NET_TX_STACK_SIZE=1024
CONFIG_NET_RX_STACK_SIZE=2048
CONFIG_LOCATION_WORKQUEUE_STACK_SIZE=4096

# nRF Cloud: CoAP
CONFIG_NRF_CLOUD_MQTT=n
CONFIG_NRF_CLOUD_COAP=y
CONFIG_NRF_CLOUD_LOCATION=n
CONFIG_NRF_CLOUD_JWT_SOURCE_CUSTOM=y

# General config
CONFIG_FPU=y

# Rate of cloud interactions
# These are faster than one normally would use in a low power device.
# This is strictly for demo purposes.
CONFIG_SENSOR_SAMPLE_INTERVAL_SECONDS=120
CONFIG_LOCATION_TRACKING_SAMPLE_INTERVAL_SECONDS=360

# Logs
CONFIG_NET_LOG=y
CONFIG_LOG_PRINTK=y
CONFIG_COAP_LOG_LEVEL_INF=y
CONFIG_LOCATION_LOG_LEVEL_INF=y

# Network
CONFIG_POSIX_API=y
CONFIG_NET_SOCKETS_TLS_SET_MAX_FRAGMENT_LENGTH=y
CONFIG_NET_SOCKETS_OFFLOAD_PRIORITY=40

# CoAP Client
CONFIG_COAP_CLIENT_BLOCK_SIZE=1024
CONFIG_COAP_CLIENT_STACK_SIZE=3072
CONFIG_COAP_CLIENT_THREAD_PRIORITY=0
CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=40
# Wi-Fi RTT to nRF Cloud can be high; give CON transfers more time.
CONFIG_COAP_INIT_ACK_TIMEOUT_MS=4000
CONFIG_COAP_MAX_RETRANSMIT=8

# Location Services configuration
CONFIG_LOCATION_DATA_DETAILS=n

CONFIG_TEMP_ALERT_LIMIT=24

# Disabling to prevent IPv6 error logs
CONFIG_NET_IPV6=n
CONFIG_NET_IPV6_NBR_CACHE=n
CONFIG_NET_IPV6_MLD=n
