#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# We keep FOTA support in a separate file because not all targets
# are able to support it yet (nRF7120/ns). Can be merged into
# coap.conf once things are in shape.

# Set sample-local flag
CONFIG_SAMPLE_MEMFAULT_FOTA=y

# Enable FOTA
CONFIG_FOTA_DOWNLOAD=y
CONFIG_FOTA_DOWNLOAD_PROGRESS_EVT=y
CONFIG_DFU_TARGET=y
CONFIG_DOWNLOADER=y
CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y
CONFIG_REBOOT=y
# CONFIG_NRF_CLOUD_FOTA and CONFIG_NRF_CLOUD_COAP_DOWNLOADS
# are still needed even for Memfault FOTA
CONFIG_NRF_CLOUD_FOTA=y
CONFIG_NRF_CLOUD_COAP_DOWNLOADS=y

# Custom callback to gracefully disconnect from nRF Cloud before reboot
CONFIG_MEMFAULT_FOTA_DOWNLOAD_CALLBACK_CUSTOM=y
# Let Memfault SDK poll for FOTA updates
CONFIG_MEMFAULT_PERIODIC_FOTA_CHECK=y

CONFIG_COAP_CLIENT_MAX_PATH_LENGTH=192
CONFIG_DOWNLOADER_MAX_FILENAME_SIZE=400
CONFIG_DOWNLOADER_STACK_SIZE=8192
