#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Select MQTT as the transport for nRF Cloud
CONFIG_NRF_CLOUD_MQTT=y

## Configure MBEDTLS for MQTT/TLS
CONFIG_MQTT_LIB_TLS=y
CONFIG_MBEDTLS_SSL_SRV_C=n
CONFIG_MBEDTLS_SSL_COOKIE_C=n
