#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_MEMFAULT=y
CONFIG_MEMFAULT_HEAP_STATS=y
CONFIG_MEMFAULT_LOGGING_ENABLE=y
CONFIG_MEMFAULT_LOGGING_RAM_SIZE=2048
CONFIG_MEMFAULT_COREDUMP_FULL_THREAD_STACKS=y

CONFIG_MEMFAULT_PERIODIC_UPLOAD=y
CONFIG_MEMFAULT_PERIODIC_UPLOAD_LOGS=n
CONFIG_MEMFAULT_HTTP_ENABLE=n
CONFIG_MEMFAULT_EVENT_STORAGE_SIZE=1024
CONFIG_MEMFAULT_COREDUMP_COLLECT_BSS_REGIONS=y
## Disable location metrics due to not being properly implemented for external handling of location
## requests when using the location library.
CONFIG_MEMFAULT_NCS_LOCATION_METRICS=n
CONFIG_MEMFAULT_PERIODIC_UPLOAD_INTERVAL_SECS=15
CONFIG_MEMFAULT_METRICS_HEARTBEAT_INTERVAL_SECS=15

# Certificate management
CONFIG_MODEM_KEY_MGMT=y

# Memfault NCS integration
CONFIG_MEMFAULT_NCS_LTE_METRICS=n
CONFIG_MEMFAULT_NCS_STACK_METRICS=y
CONFIG_MEMFAULT_NCS_INTERNAL_FLASH_BACKED_COREDUMP=y
CONFIG_MEMFAULT_NCS_POST_COREDUMP_ON_NETWORK_CONNECTED=n
CONFIG_MEMFAULT_NCS_POST_COREDUMP_RETRIES_MAX=10

# Memfault depends on POSIX, disable unneeded POSIX features
CONFIG_POSIX_FILE_SYSTEM=n

# CoAP
CONFIG_MEMFAULT_USE_NRF_CLOUD_COAP=y
CONFIG_NRF_CLOUD_COAP_MAX_USER_OPTIONS=2
CONFIG_COAP_CLIENT_MAX_EXTRA_OPTIONS=3
