#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_POWER_DOMAIN=n

CONFIG_PSA_CRYPTO=y
CONFIG_MULTITHREADING=y

CONFIG_NRF_BOOT_FIRMWARE_LOADER_BOOT_REQ=y
CONFIG_NRF_MCUBOOT_BOOT_REQUEST=y
CONFIG_CRC=y
