CONFIG_FLASH=y
CONFIG_MAIN_STACK_SIZE=10240
CONFIG_FPROTECT=n

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

CONFIG_NRF_OBERON=y
CONFIG_BOOT_ECDSA_NRF_OBERON=y

CONFIG_NCS_BOOT_BANNER=n
CONFIG_MCUBOOT_BOOT_BANNER=n
CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=n
CONFIG_MINIMAL_LIBC=y
CONFIG_SYS_CLOCK_EXISTS=n
CONFIG_GPIO=n

CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
CONFIG_LTO=y
