#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_LOG=y

CONFIG_SOC_NRF54H20_CPURAD_ENABLE=y

# Enable S2RAM
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_POWEROFF=y

# Set the version number for the firmware to verify dfu process
#CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.0.1+0"
