#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Extra conf file for mutual DTLS.

# Different cert file than in the default HTTPS case.
CONFIG_SAMPLE_CERT_FILE="cert/cf-ca.pem"
# Mutual DTLS. Client cert and key are under cert/.
CONFIG_SAMPLE_PROVISION_CLIENT_CERT=y

# The file to download.
CONFIG_SAMPLE_FILE_CUSTOM=y
CONFIG_SAMPLE_FILE_URL="coaps://californium.eclipseprojects.io/large"
CONFIG_SAMPLE_SHA256_HASH="a26bd312022f497cb0c9451aa145b04fd5ceab7af0da59766a8bbb962e60d872"
