#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_BT_CTLR_EXTENDED_FEAT_SET=y
CONFIG_BT_CTLR_SUBRATING=y
CONFIG_BT_CTLR_SHORTER_CONNECTION_INTERVALS=y

# 254 is the minimum required CONFIG_BT_BUF_EVT_RX_SIZE to support
# HID SCI information read.
CONFIG_BT_BUF_EVT_RX_SIZE=254
