#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Secure Storage is needed to enable the Protected Storage TLS credentials backend
# (persists TLS credentials across reboots) when TF-M is not in use.
CONFIG_SECURE_STORAGE=y
# Secure Storage stores its data through Settings on ZMS.
CONFIG_FLASH=y
CONFIG_ZMS=y
CONFIG_SETTINGS=y
