#!/usr/bin/env python3
#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: Apache-2.0
"""Generate Zephyr sample to Nordic board target mapping for NCS documentation.

The script scans sample.yaml files in the Zephyr tree and in nrf/samples/zephyr,
collects platform_allow entries for Nordic boards, and writes an RST include file
used by the documentation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

NORDIC_BOARD_PREFIXES = ("nrf",)
EXCLUDED_BOARD_PREFIXES = ("qemu", "nrf51", "native")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    default_nrf = Path(__file__).resolve().parents[2]
    parser.add_argument(
        "--nrf-base",
        type=Path,
        default=default_nrf,
        help="Path to the nrf repository root.",
    )
    parser.add_argument(
        "--zephyr-base",
        type=Path,
        default=default_nrf.parent / "zephyr",
        help="Path to the Zephyr repository root.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_nrf / "doc/nrf/includes/zephyr_nordic_sample_boards.rst",
        help="Path to the generated RST include file.",
    )
    return parser.parse_args()


def _is_nordic_board(board: str) -> bool:
    first = board.split("/", maxsplit=1)[0]
    if first.startswith(EXCLUDED_BOARD_PREFIXES):
        return False
    return first.startswith(NORDIC_BOARD_PREFIXES)


def _as_list(value: str | list[str]) -> list[str]:
    if isinstance(value, str):
        return [value]
    return list(value)


def _platform_allow_from_yaml(data: dict) -> set[str]:
    boards: set[str] = set()

    common = data.get("common", {})
    if "platform_allow" in common:
        boards.update(_as_list(common["platform_allow"]))

    for test in data.get("tests", {}).values():
        if "platform_allow" in test:
            boards.update(_as_list(test["platform_allow"]))

    return {board for board in boards if _is_nordic_board(board)}


def _collect_samples(
    samples_root: Path,
    key_from_path,
) -> dict[str, dict[str, set[str] | str]]:
    samples: dict[str, dict[str, set[str] | str]] = {}

    if not samples_root.exists():
        return samples

    for sample_yaml in sorted(samples_root.glob("**/sample.yaml")):
        with sample_yaml.open(encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}

        boards = _platform_allow_from_yaml(data)
        if not boards:
            continue

        key = key_from_path(sample_yaml, samples_root)
        entry = samples.setdefault(
            key,
            {
                "name": data.get("sample", {}).get("name", key),
                "boards": set(),
            },
        )
        if name := data.get("sample", {}).get("name"):
            entry["name"] = name
        entry["boards"].update(boards)

    return samples


def _merge_samples(
    upstream: dict[str, dict[str, set[str] | str]],
    extended: dict[str, dict[str, set[str] | str]],
) -> dict[str, dict[str, set[str] | str]]:
    merged = dict(upstream)
    for key, entry in extended.items():
        if key in merged:
            merged[key]["boards"].update(entry["boards"])
            if entry.get("name"):
                merged[key]["name"] = entry["name"]
        else:
            merged[key] = entry
    return merged


def _format_board_targets(boards: set[str]) -> str:
    return ", ".join(f"``{board}``" for board in sorted(boards))


def _render_rst(samples: dict[str, dict[str, set[str] | str]]) -> str:
    lines = [
        ".. Generated by scripts/doc/gen_zephyr_nordic_sample_boards.py.",
        ".. Do not edit manually.",
        "",
        ".. list-table:: Zephyr samples with Nordic board targets",
        "   :header-rows: 1",
        "   :widths: 28 22 50",
        "",
        "   * - Sample path",
        "     - Sample name",
        "     - Board targets",
    ]

    for key in sorted(samples):
        entry = samples[key]
        boards = entry["boards"]
        name = entry["name"]
        lines.append(f"   * - ``samples/{key}``")
        lines.append(f"     - {name}")
        lines.append(f"     - {_format_board_targets(boards)}")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = _parse_args()
    zephyr_samples = args.zephyr_base / "samples"
    nrf_extended = args.nrf_base / "samples/zephyr"

    upstream = _collect_samples(
        zephyr_samples,
        lambda path, root: path.parent.relative_to(root).as_posix(),
    )
    extended = _collect_samples(
        nrf_extended,
        lambda path, root: path.parent.relative_to(root).as_posix(),
    )
    merged = _merge_samples(upstream, extended)

    if not merged:
        raise SystemExit(
            "No Nordic board mappings found. Check --zephyr-base and --nrf-base."
        )

    output = _render_rst(merged)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    print(f"Wrote {len(merged)} samples to {args.output}")


if __name__ == "__main__":
    main()
