;
; Copyright (c) 2024 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;

; PRNG random number request.
prng_req = [
	length: uint,
]

; PRNG random number response.
prng_rsp = [
	status: int,
	buffer: bstr,
]
