# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# PROTECTEDMEM and UICR.SNAPSHOT.REGIONS are configured from the UICR image;
# see sysbuild/uicr.conf.

CONFIG_BOOT_BANNER=y
CONFIG_NCS_BOOT_BANNER=n

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_MAIN_STACK_SIZE=2048
