;
; Copyright (c) 2021 Nordic Semiconductor ASA
;
; SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
;


Segment = (
    target_addr: uint,
    len: uint
)

Segments = [ + Segment ]

Manifest = [
    version: uint,
    compat: uint,
    blob_hash: bstr .size 32,
    segments: bstr .cbor Segments
]

Wrapper = #6.18(COSE_Sign1_Manifest)

COSE_Sign1_Manifest = [
    protected: bstr .cbor header_map,
    unprotected: {},
    payload : bstr .cbor Manifest,
    signature : bstr .size 256
]

header_map = {
    1 => sign_RSA256  ; algorithm identifier
}

sign_RSA256 = -37 ; RSASSA-PSS, SHA256

Sig_structure1 = [
    context : "Signature1",
    body_protected : bstr .cbor header_map,
    external_aad : '',   ; 0 length bstr
    payload : bstr
]
