/*TODO: Remove when multi-image has been merged*/
#ifndef BOOTLOADER_H__
#define BOOTLOADER_H__

#include <autoconf.h>
#define ROM_ADDR_SIZE (CONFIG_FLASH_SIZE * 1024)
#define DT_FLASH_AREA_PROVISION_SIZE		0x1000
#define DT_FLASH_AREA_PROVISION_OFFSET	(ROM_ADDR_SIZE - DT_FLASH_AREA_PROVISION_SIZE)

#if CONFIG_SOC_NRF52840  ||\
	CONFIG_SOC_NRF52832  ||\
	CONFIG_SOC_NRF52810  ||\
	CONFIG_NRF51822_QFAA ||\
	CONFIG_NRF51822_QFAB ||\
	CONFIG_NRF51822_QFAC
/* partition@0 */

#define DT_FLASH_AREA_SECURE_BOOT_OFFSET	0x0
#define DT_FLASH_AREA_SECURE_BOOT_SIZE		0x4000

/* partition@4000 */
#define DT_FLASH_AREA_S0_OFFSET		0x4000
#define DT_FLASH_AREA_S0_SIZE		0xc000

/* partition@10000 */
#define DT_FLASH_AREA_S1_OFFSET		0x10000
#define DT_FLASH_AREA_S1_SIZE		0xc000

/* partition@1C000 */
#define DT_FLASH_AREA_APP_OFFSET	0x1c000
#define DT_FLASH_AREA_APP_SIZE		(ROM_ADDR_SIZE - DT_FLASH_AREA_APP_OFFSET - DT_FLASH_AREA_PROVISION_SIZE)

#elif CONFIG_SOC_NRF9160
/* partition@0 */
#define DT_FLASH_AREA_SECURE_BOOT_OFFSET	0x0
#define DT_FLASH_AREA_SECURE_BOOT_SIZE		0x8000

/* partition@8000 */
#define DT_FLASH_AREA_S0_OFFSET		0x8000
#define DT_FLASH_AREA_S0_SIZE		0x4000

/* partition@C000 */
#define DT_FLASH_AREA_S1_OFFSET		0xc000
#define DT_FLASH_AREA_S1_SIZE		0x4000

/* partition@10000 */
#define DT_FLASH_AREA_APP_OFFSET	0x10000
#define DT_FLASH_AREA_APP_SIZE		(ROM_ADDR_SIZE - DT_FLASH_AREA_APP_OFFSET - DT_FLASH_AREA_PROVISION_SIZE)

#else
#error "Board not supported for SECURE BOOT"
#endif /* CONFIG_SOC_NRF52840 */
#endif /* BOOTLOADER_H__ */

