#
# Copyright (c) 2023 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG=n
CONFIG_TIMESLICE_SIZE=0

# Enable old clock_control_nrf api implementation for mpsl to use
CONFIG_CLOCK_CONTROL_NRF=y
