CONFIG_LOG=y
CONFIG_LOG_BUFFER_SIZE=2048

CONFIG_RING_BUFFER=y

CONFIG_BT=y
CONFIG_BT_ISO_BROADCASTER=y
CONFIG_BT_ISO_CENTRAL=y

CONFIG_BT_CTLR_ADV_ISO_STREAM_COUNT=1
CONFIG_BT_CTLR_SYNC_ISO_STREAM_COUNT=1
CONFIG_BT_CTLR_CONN_ISO_STREAMS=1
CONFIG_BT_DEVICE_NAME="Nordic_BIS_CIS"
CONFIG_BT_MAX_CONN=2

CONFIG_BT_ISO_TX_BUF_COUNT=1
CONFIG_BT_ISO_RX_BUF_COUNT=1

CONFIG_BT_ISO_TX_MTU=5

CONFIG_BT_CTLR_SDC_CENTRAL_ACL_EVENT_SPACING_DEFAULT=10000
CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=2500