CONFIG_NRFX_RRAMC=y

CONFIG_NRFX_CLOCK=n

CONFIG_NRFX_I2S=n

CONFIG_DISK_DRIVERS=n
CONFIG_DISK_DRIVER_SDMMC=n

CONFIG_FILE_SYSTEM=n
CONFIG_FAT_FILESYSTEM_ELM=n
CONFIG_FS_FATFS_LFN=n
CONFIG_FS_FATFS_LFN_MODE_STACK=n
CONFIG_FS_FATFS_EXFAT=n

CONFIG_NRFX_NVMC=n
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
