/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef LOG_RPC_H_
#define LOG_RPC_H_

#include <stddef.h>

/**
 * @file
 * @defgroup log_rpc nRF RPC logging
 * @{
 * @brief Logging over nRF RPC
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * nRF RPC logging level.
 */
enum log_rpc_level {
	LOG_RPC_LEVEL_NONE = 0,
	LOG_RPC_LEVEL_ERR,
	LOG_RPC_LEVEL_WRN,
	LOG_RPC_LEVEL_INF,
	LOG_RPC_LEVEL_DBG,
};

/**
 * Log history handler.
 *
 * The type of a callback function that is invoked for each received log message
 * while fetching the log history from the remote device.
 *
 * @param level		The message level, see @c log_rpc_level.
 * @param msg		A pointer to the message payload.
 * @param msg_len	The message payload length.
 */
typedef void (*log_rpc_history_handler_t)(enum log_rpc_level level, const char *msg,
					  size_t msg_len);

/**
 * Sets the log streaming verbosity level.
 *
 * The log streaming is the feature of nRF RPC logging that allows receiving log
 * messages as they are generated by the application running on the remote device.
 *
 * This function issues an nRF RPC command that configures the remote device to
 * stream log messages whose level is less than or equal to the specified level.
 *
 * @param level		Logging level, see @c log_rpc_level.
 *
 * @retval 0		On success.
 * @retval -errno	On failure.
 */
int log_rpc_set_stream_level(enum log_rpc_level level);

/**
 * Sets the log history verbosity level.
 *
 * The log history is the feature of nRF RPC logging that allows saving log
 * messages generated by the application running on the remote device into
 * a ring buffer, and then retrieving the log history when needed.
 *
 * The function issues an nRF RPC command that configures the remote device to
 * save log messages whose level is less than or equal to the specified level.
 *
 * @param level		Logging level, see @c log_rpc_level.
 *
 * @retval 0		On success.
 * @retval -errno	On failure.
 */
int log_rpc_set_history_level(enum log_rpc_level level);

/**
 * Fetches the log history.
 *
 * The function issues an nRF RPC command that starts the log history transfer
 * from the remote device. The @c handler callback function is invoked for each
 * received log message. Additionally, it is invoked with @c msg argument set to
 * NULL after all log messages have been received.
 *
 * @note If the function is called while the previous log history transfer is
 *       still is in progress, the process is restarted from the current oldest
 *       log message saved in the log history on the remote device.
 *
 * @param handler	History handler, see @c log_rpc_history_handler_t.
 *
 * @retval 0		On success.
 * @retval -errno	On failure.
 */
int log_rpc_fetch_history(log_rpc_history_handler_t handler);

/**
 * @brief Retrieves the crash log retained on the remote device.
 *
 * The function issues an nRF RPC command to obtain the last crash log retained
 * on the remote device, and then it copies the received log chunk into the
 * specified buffer.
 *
 * The remote may either send the entire crash log in one go, if it fits within
 * the output buffer, or it may send a chunk of the log. Therefore, the caller
 * should repeatedly call this function, with an increasing offset, until it
 * returns 0 (indicating no more data), or a negative value (indicated an error).
 *
 * @param offset        Crash log offset.
 * @param buffer        Output buffer to copy the received log chunk.
 * @param buffer_length Output buffer length.
 *
 * @returns             The number of characters copied into the output buffer.
 * @returns -errno      Indicates failure.
 */
int log_rpc_get_crash_log(size_t offset, char *buffer, size_t buffer_length);

#ifdef __cplusplus
}
#endif

/**
 *@}
 */

#endif /* LOG_RPC_H_ */
