CONFIG_MBEDTLS_HEAP_SIZE=75000
CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
CONFIG_WIFI_NM_WPA_SUPPLICANT_THREAD_STACK_SIZE=12000
CONFIG_TLS_CREDENTIALS_BACKEND_PROTECTED_STORAGE=y
CONFIG_NRF_WIFI_DATA_HEAP_SIZE=92000
