# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BUFFER_SIZE=16384

CONFIG_NET_L2_DECT_LOG_LEVEL_INF=y
CONFIG_NET_L2_DECT_BR_LOG_LEVEL_INF=y
CONFIG_NET_L2_DECT_CONN_MGR_LOG_LEVEL_INF=y
CONFIG_NET_L2_DECT_MGMT_LOG_LEVEL_INF=y

CONFIG_NET_CORE_LOG_LEVEL_INF=y
CONFIG_NET_IF_LOG_LEVEL_INF=y
CONFIG_NET_IPV6_ROUTE_LOG_LEVEL_DBG=y
CONFIG_NET_IPV6_LOG_LEVEL_INF=y
CONFIG_NET_IPV6_ND_LOG_LEVEL_DBG=y
CONFIG_NET_IPV6_NBR_CACHE_LOG_LEVEL_INF=y
CONFIG_NET_L2_ETHERNET_LOG_LEVEL_INF=y
CONFIG_ETHERNET_LOG_LEVEL_INF=y

CONFIG_NET_CONNECTION_MANAGER_LOG_LEVEL_INF=y
CONFIG_NET_MGMT_EVENT_LOG_LEVEL_INF=y
