# IO
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

# Assertions
CONFIG_ASSERT=y

# hci_raw
CONFIG_BT=y
CONFIG_BT_HCI_RAW=y
CONFIG_BT_HCI_RAW_H4=y
CONFIG_BT_HCI_RAW_H4_ENABLE=y

# Data buffers
CONFIG_NET_BUF=y
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_BUF_EVT_RX_SIZE=255

# PHYs
CONFIG_BT_CTLR_PHY_CODED=y

# DTM
CONFIG_BT_CTLR_DTM_HCI=y
CONFIG_BT_CTLR_DTM_HCI_RX_V3=n

# DTM 2-wire to HCI
CONFIG_BT_CTLR_EXTENDED_FEAT_SET=y
CONFIG_DTM_TWOWIRE_TO_HCI=y

# Logging
# To enable logging for this sample, assign 'y' to these options
CONFIG_LOG=n
CONFIG_LOG_PRINTK=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
