#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_HW_STACK_PROTECTION=n

CONFIG_BOOT_WATCHDOG_FEED=n

# nRF54LM20DK uses SPI NOR external flash
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096

# required by SPI driver
CONFIG_MULTITHREADING=y

CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

# Disable CRACEN KMU
CONFIG_CRACEN_LIB_KMU=n

# Make sure oberon driver is enabled
CONFIG_PSA_CRYPTO_DRIVER_OBERON=y
# Enable CRACEN driver
CONFIG_PSA_CRYPTO_DRIVER_CRACEN=y
# Fallback to oberon driver for cipher operations (AES-modes)
CONFIG_PSA_USE_CRACEN_CIPHER_DRIVER=n
# Fallback to oberon for authenticated encryption (AES-GCM, CCM, Chachapoly)
CONFIG_PSA_USE_CRACEN_AEAD_DRIVER=n
# Fallback to oberon for hashes (SHA-*)
CONFIG_PSA_USE_CRACEN_HASH_DRIVER=n
# Fallback to oberon for MAC (CMAC, HMAC)
CONFIG_PSA_USE_CRACEN_MAC_DRIVER=n
# Fallback to oberon for ECDH
CONFIG_PSA_USE_CRACEN_KEY_AGREEMENT_DRIVER=n
# Fallback to oberon for asymmetric encryption
CONFIG_PSA_USE_CRACEN_ASYMMETRIC_DRIVER=n
# Fallback to oberon for all key management
CONFIG_PSA_USE_CRACEN_KEY_MANAGEMENT_DRIVER=n
# Fallback to oberon nfor KDFs
CONFIG_PSA_USE_CRACEN_KEY_DERIVATION_DRIVER=n
# Fallback to oberon for PAKES (EC J-PAKE, SPAKE2+)
CONFIG_PSA_USE_CRACEN_PAKE_DRIVER=n
# Fallback to oberon for signatures (ECDSA, EDDSA, RSA)
CONFIG_PSA_USE_CRACEN_ASYMMETRIC_SIGNATURE_DRIVER=n
