#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Development-oriented options: asserts and DBG log levels for this sample and
# nRF RPC modules. For manual use, pass e.g.:
#   -- -DEXTRA_CONF_FILE=verbose.conf

# Enable asserts
CONFIG_ASSERT=y

# Enable verbose logging
CONFIG_NRF_PS_CLIENT_LOG_LEVEL_DBG=y
CONFIG_NRF_RPC_TR_LOG_LEVEL_DBG=y
CONFIG_NRF_RPC_LOG_LEVEL_DBG=y
CONFIG_NRF_RPC_OS_LOG_LEVEL_DBG=y
