#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Enables MPSL Software Coexistence for this sample.
#
# Note: This sample requires applying :file:`coex.overlay` explicitly (pass it
# via EXTRA_DTC_OVERLAY_FILE) together with this Kconfig fragment.
#

CONFIG_MPSL_CX=y
CONFIG_MPSL_CX_SOFTWARE=y
