# Enable UICR.LOCK to protect the UICR area
CONFIG_GEN_UICR_LOCK=y

# Configure PROTECTEDMEM to protect [MCUboot, MPCCONF blob, PERIPHCONF blob]
CONFIG_GEN_UICR_PROTECTEDMEM=y
CONFIG_GEN_UICR_PROTECTEDMEM_SIZE_BYTES=65536
