#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Wi-Fi only radio test overlay
# Disables peripheral BLE radio test functionality and dependencies

# Disable peripheral radio test shell/console
CONFIG_CONSOLE_HANDLER=n

# Disable peripheral radio test BLE-specific features
CONFIG_FEM_AL_LIB=n
CONFIG_ENTROPY_GENERATOR=n
CONFIG_PSA_CRYPTO=n
CONFIG_NRFX_TIMER=n
CONFIG_DYNAMIC_INTERRUPTS=n
