#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Build the TF-M provisioning image as a separate, build-only image.
#
# On nRF54L this is the default way to provision the device for this application.
# The application does not provision itself, so the provisioning image (which
# writes key material and advances the PSA lifecycle state) is built alongside it
# and must be flashed before it. Because provisioning is a separate image, this
# also supports split-production flows, where provisioning is performed in a
# secure environment that is separate from where the application firmware is
# programmed.
#
# The image is added with BUILD_ONLY, so it is excluded from "west flash" and
# from any merged hex. The keyfile.json used to provision the NSIB public key to
# the CRACEN KMU is generated by this application's b0 configuration
# (SB_CONFIG_SECURE_BOOT_GENERATE_DEFAULT_KMU_KEYFILE) and is picked up
# automatically when flashing the provisioning image domain, so the provisioning
# image does not generate its own when built here.
#
# Flash it before the application, e.g.:
#   west flash --recover --domain provisioning_image
if(SB_CONFIG_SAMPLE_PROVISIONING_IMAGE)
  # The provisioning image runs before TF-M is installed, so it must be built for
  # the secure board target. Derive it from the (non-secure) application board
  # target by stripping the trailing "/ns" qualifier, for example:
  #   nrf54l15dk/nrf54l15/cpuapp/ns -> nrf54l15dk/nrf54l15/cpuapp
  # In this scope BOARD_QUALIFIERS has no leading slash, so it is joined with "/".
  string(REGEX REPLACE "/ns$" "" provisioning_image_qualifiers "${BOARD_QUALIFIERS}")
  if(DEFINED BOARD_REVISION)
    set(provisioning_image_board "${BOARD}@${BOARD_REVISION}/${provisioning_image_qualifiers}")
  else()
    set(provisioning_image_board "${BOARD}/${provisioning_image_qualifiers}")
  endif()

  ExternalZephyrProject_Add(
    APPLICATION provisioning_image
    SOURCE_DIR ${ZEPHYR_NRF_MODULE_DIR}/samples/tfm/provisioning_image
    BOARD ${provisioning_image_board}
    BUILD_ONLY true
  )

  # Undo the build-wide APPROTECT lock for this image only, so that the
  # application can still be programmed after the device has been provisioned.
  # See the script for details.
  set_property(TARGET provisioning_image APPEND PROPERTY IMAGE_CONF_SCRIPT
    ${CMAKE_CURRENT_LIST_DIR}/sysbuild/provisioning_image_approtect.cmake
  )

  set(provisioning_image_qualifiers)
  set(provisioning_image_board)
endif()
