#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Full content from bootloader/mcuboot/boot/zephyr/prj.conf - required because
# sysbuild uses this file as the sole prj.conf for the mcuboot image when a
# sysbuild/mcuboot/ directory is present.
CONFIG_PM=n

CONFIG_MAIN_STACK_SIZE=10240

CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n

CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_BOOTSTRAP=n

CONFIG_FLASH=y

# CONFIG_BT is not set
# CONFIG_I2C is not set
