#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Multirole is the only currently supported role by SoftDevice.
CONFIG_BT_LL_SOFTDEVICE_MULTIROLE=y

# ZMS cache optimization
CONFIG_ZMS_LOOKUP_CACHE=y
CONFIG_ZMS_LOOKUP_CACHE_SIZE=512
CONFIG_ZMS_LOOKUP_CACHE_FOR_SETTINGS=y

# Workaround required as Zephyr L2 implies usage of NVS backend for settings.
# It should be removed once the proper fix will be applied in Zephyr.
CONFIG_NVS=n

# Disable SPI
CONFIG_CHIP_SPI_NOR=n

# Do not use CRACEN KMU in Matter yet
CONFIG_CHIP_CRYPTO_PSA_DAC_PRIV_KEY_ITS=y
CONFIG_TRUSTED_STORAGE_BACKEND_AEAD_KEY_HASH_UID=y
CONFIG_CRACEN_LIB_KMU=n

# Make sure oberon driver is enabled
CONFIG_PSA_CRYPTO_DRIVER_OBERON=y
# Enable CRACEN driver
CONFIG_PSA_CRYPTO_DRIVER_CRACEN=y
# Fallback to oberon driver for cipher operations (AES-modes)
CONFIG_PSA_USE_CRACEN_CIPHER_DRIVER=n
# Fallback to oberon for authenticated encryption (AES-GCM, CCM, Chachapoly)
CONFIG_PSA_USE_CRACEN_AEAD_DRIVER=n
# Fallback to oberon for hashes (SHA-*)
CONFIG_PSA_USE_CRACEN_HASH_DRIVER=n
# Fallback to oberon for MAC (CMAC, HMAC)
CONFIG_PSA_USE_CRACEN_MAC_DRIVER=n
# Fallback to oberon for ECDH
CONFIG_PSA_USE_CRACEN_KEY_AGREEMENT_DRIVER=n
# Fallback to oberon for asymmetric encryption
CONFIG_PSA_USE_CRACEN_ASYMMETRIC_DRIVER=n
# Fallback to oberon for all key management
CONFIG_PSA_USE_CRACEN_KEY_MANAGEMENT_DRIVER=n
# Fallback to oberon nfor KDFs
CONFIG_PSA_USE_CRACEN_KEY_DERIVATION_DRIVER=n
# Fallback to oberon for PAKES (EC J-PAKE, SPAKE2+)
CONFIG_PSA_USE_CRACEN_PAKE_DRIVER=n
# Fallback to oberon for signatures (ECDSA, EDDSA, RSA)
CONFIG_PSA_USE_CRACEN_ASYMMETRIC_SIGNATURE_DRIVER=n
