/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef BL_PARTITIONS_H
#define BL_PARTITIONS_H

#if defined(CONFIG_PARTITION_MANAGER_ENABLED)

#include <pm_config.h>
#define NSIB_B0_ADDRESS PM_B0_ADDRESS
#define NSIB_B0_SIZE PM_B0_SIZE
#define NSIB_PROVISION_ADDRESS PM_PROVISION_ADDRESS
#define NSIB_PROVISION_SIZE PM_PROVISION_SIZE

#if defined(PM_S0_ADDRESS)
#define NSIB_S0_ADDRESS PM_S0_ADDRESS
#define NSIB_S0_SIZE PM_S0_SIZE
#endif
#if defined(PM_S1_ADDRESS)
#define NSIB_S1_ADDRESS PM_S1_ADDRESS
#define NSIB_S1_SIZE PM_S1_SIZE
#endif

#else /* defined(CONFIG_PARTITION_MANAGER_ENABLED) */

#define NSIB_B0_CONTAINER_NODE B0 DT_GPARENT(DT_NODELABEL(b0_partition))
#define NSIB_B0_CONTAINER_ADDRESS DT_REG_ADDR(NSIB_B0_CONTAINER_NODE)
#define NSIB_B0_CONTAINER_SIZE DT_REG_SIZE(SOC_NV_FLASH_NODE_B0)
#define NSIB_B0_OFFSET DT_REG_ADDR(DT_NODELABEL(b0_partition))
#define NSIB_B0_ADDRESS (NSIB_B0_CONTAINER_ADDRESS + NSIB_B0_OFFSET)
#define NSIB_B0_SIZE DT_REG_SIZE(DT_NODELABEL(b0_partition))

#define NSIB_PROVISION_CONTAINER_NODE DT_GPARENT(DT_NODELABEL(provision_partition))
#define NSIB_PROVISION_CONTAINER_ADDRESS DT_REG_ADDR(NSIB_PROVISION_CONTAINER_NODE)
#define NSIB_PROVISION_OFFSET DT_REG_ADDR(DT_NODELABEL(provision_partition))
#define NSIB_PROVISION_ADDRESS (NSIB_PROVISION_CONTAINER_ADDRESS + NSIB_PROVISION_OFFSET)
#define NSIB_PROVISION_SIZE DT_REG_SIZE(DT_NODELABEL(provision_partition))

#define NSIB_S0_SIZE DT_REG_SIZE(DT_NODELABEL(s0_partition))
#define NSIB_S1_SIZE DT_REG_SIZE(DT_NODELABEL(s1_partition))

#endif /* defined(CONFIG_PARTITION_MANAGER_ENABLED) */

#endif /* BL_PARTITIONS_H */
