#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y

CONFIG_BT=y
CONFIG_BT_HCI_RAW=y
#CONFIG_BT_MAX_CONN=16

# 254 is the minimum CONFIG_BT_BUF_EVT_RX_SIZE to support bt_conn_le_read_min_conn_interval_groups.
# This function is used by in order to load HID SCI information.
CONFIG_BT_BUF_EVT_RX_SIZE=254

CONFIG_BT_MAX_CONN=2
CONFIG_BT_CENTRAL=n

CONFIG_IPC_RADIO_BT=y
CONFIG_IPC_RADIO_BT_HCI_IPC=y

CONFIG_BT_CTLR_EXTENDED_FEAT_SET=y
CONFIG_BT_CTLR_SUBRATING=y
CONFIG_BT_CTLR_SHORTER_CONNECTION_INTERVALS=y

# Optimize for best possible performance in HID SCI FAST mode

# Keep the maximum connection event below the minimum connection interval of 875 us
# Without this, the effective minimum connection interval is 1125 us.
CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=750
