/*
 * Copyright (c) 2019 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */
#ifndef PSA_CRYPTO_LITE__
#define PSA_CRYPTO_LITE__

#include "assert.h"
#include "zephyr/sys/util_macro.h"
#include <psa/crypto.h>

#define LIST_CHECK_SAME(a, b) a == b

#define IF_FALSE_RETURN(x) do { if ((x)) { return PSA_ERROR_NOT_SUPPORTED; } } while (0)

/** Macro to check multiple items to that at least one is matched
 *
 * if-statement(s) with return will be generated by preprocessor
 * unless CONFIG_PSA_CRYPTO_LITE_DISABLE_CHECKS is set
 */
#define VERIFY_PSA_TYPE_AT_LEAST_ONE_RETURNS(alg, ...)				\
	IF_FALSE_RETURN(FOR_EACH_FIXED_ARG(LIST_CHECK_SAME, (||),		\
					   alg, LIST_DROP_EMPTY(__VA_ARGS__)))

#endif /* PSA_CRYPTO_LITE__ */
