CONFIG_MSPI=y
CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_BACKEND_ICMSG=y
CONFIG_PBUF_RX_READ_BUF_SIZE=768

# Runtime PM for hpf_mspi (zephyr,pm-device-runtime-auto in hpf-mspi-app.overlay)
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Additional compiler flags
CONFIG_COMPILER_OPT="-fshort-enums"
