# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

#
# Modem power is controlled by VPR core when building with radio_test
#
CONFIG_GPIO_HOGS=n
CONFIG_POWER_DOMAIN_GPIO=n

#
# Start the VPR core last, so PMIC is initialized before
#
CONFIG_NORDIC_VPR_LAUNCHER_INIT_PRIORITY=200
