name: Documentation Publish

on:
  workflow_run:
    workflows: ["Documentation Build"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Publish
        uses: nrfconnect/action-docpublish@a272d73b3f083e41287e32068a0e4c3aef622c21
        with:
          storage-url: ${{ vars.NCS_DOC_STORAGE_URL }}
          storage-url-pr: ${{ vars.NCS_DOC_PR_STORAGE_URL }}
          storage-sas: ${{ secrets.NCS_DOC_SAS_MAIN }}
          storage-pr-sas: ${{ secrets.NCS_DOC_SAS_PRS }}
